<a href="https://colab.research.google.com/github/saritasaksu47-boop/python/blob/main/python_for_generative_AI_G3_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

mysub= "python"

mysub

'python'

In [ ]:
print(mysub)

python


In [ ]:
_mycity='solan'
print(_mycity)

solan


In [ ]:
mysub1="gen. ai"
mysub1

'gen. ai'

In [ ]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [ ]:
#data type in python
#numeric
#integer-------absence of decimal point
#ex--------1,2,3
x=1
type(x)

int

In [ ]:
#floating point number----presence of decimal point
#ex-------2.14,3.14
y=2.14
type(y)

float

In [ ]:
#complex----combo of real and imaginary
z=4+9j
type(z)

complex

In [ ]:
#string-----data in text
x="solan"

In [ ]:
#none-----no data present
e = None
type(e)

NoneType

In [ ]:
#boolgan------ to store true ND FALSE
a = True
type(a)

bool

In [ ]:
#single quote string
my_sub='gen ai'
type(my_sub)

str

In [ ]:
#double quote string
my__group=6
type(my__group)


int

In [ ]:
#triple wala
my_age='''19'''
type(my_age)

str

In [ ]:
my_sub="machine learning"
my_sub[0]

'm'

In [ ]:
#UPPER- THI METHOD CONVERTS STRING INTO UPPER CASE
my_sub="machine learning"
my_sub.upper()

'MACHINE LEARNING'

In [ ]:
#count()- this method counts particular characters in string.
my_sub="machine learning"
my_sub.count('a')

2

In [ ]:
#list - it is collection of item,

my_list = [88,98,9,87]
type(list)

type

In [ ]:
print(my_list)

[88, 98, 9, 87]


In [ ]:
mixed_list = [76,2.14,"apple","cake"]
type(mixed_list)

list

In [ ]:
#indexing in list---location of item
my_list = []

In [ ]:
#positive indexing/negative indexing
my_list = [78,90,76,54,67,78,87]
print(my_list[0])
print(my_list[3])
print(my_list[-2])

78
54
78


In [ ]:
# slicing in list - grab the data designated point is known as slicing.
my_list = [96,76,33,56]
#starting index is included- SI
#ending index is excluded - EI
my_list[0:3:2]

[96, 33]

In [ ]:
my_list[0:4]

[96, 76, 33, 56]

In [ ]:
my_list[0:]

[96, 76, 33, 56]

In [ ]:
my_list[:3]

[96, 76, 33]

In [ ]:
my_list[::-1]

[56, 33, 76, 96]

In [ ]:
#function in list
print(my_list)

[96, 76, 33, 56]


In [ ]:
min(my_list)

33

In [ ]:
max(my_list)

96

In [ ]:
sum(my_list)

261

In [ ]:
#sorted--this function arranges list in increasing/decreasing order

In [ ]:
print (my_list)

[96, 76, 33, 56]


In [ ]:
sorted(my_list)

[33, 56, 76, 96]

In [ ]:
sorted(my_list,reverse= True)

[96, 76, 56, 33]

In [ ]:
list1=[1,2,4]
list2=[8,9,7]
list1.extend(list2)
print(list1)

[1, 2, 4, 8, 9, 7]


In [ ]:
#list function does not changes the original list

In [ ]:
#append()--this method add item at the end of the list
my_list.append(100)
print(my_list)

[96, 76, 33, 56, 100]


In [ ]:
#extend()---this method merges lists

In [ ]:
#sort()--this method use to arrange list into increasing order/decreasing order.
my_list=[12,23,9,8,17]
my_list.sort()
my_list

[8, 9, 12, 17, 23]

In [ ]:
my_list.sort(reverse=True)
my_list

[23, 17, 12, 9, 8]

In [ ]:
#pop()--this method remove item from the list and take index as argument
list1=[9,8,78,67,13]
list1.pop(2)

78

In [ ]:
#remove()-it also remove an item from the list but it takes item as an argument
my_list=[89,67,54,34]
my_list.remove(89)


In [ ]:
my_list

[67, 54, 34]

In [ ]:
#dictionary--it is collection of key value pair,
# key and value separated by colon.
#the combination of key and value is known as item.every item seoarated by comma,all item are enclosed by curly braces
#my_dict={"hp":"shimla":"up":"luck"}

In [ ]:
#dicitionary
my_dict={"hp":"shimla","up":"lucknow"}
print(my_dict)

{'hp': 'shimla', 'up': 'lucknow'}


In [ ]:
print(my_dict["hp"])

shimla


In [ ]:
print(my_dict["up"])

lucknow


In [ ]:
#keys()--this method returns keys of dictionary
list(my_dict.keys())

['hp', 'up']

In [ ]:
#values()--this method find value of the dictionary
list(my_dict.values())

['shimla', 'lucknow']

In [ ]:
#items()--this method returns item of the dictionary
list(my_dict.items())

[('hp', 'shimla'), ('up', 'lucknow')]

In [ ]:
#get()--the method returns the value of the dictionary and take keys as arguments
my_dict.get("hp")

'shimla'

In [ ]:
#update()---this method upadtes the dict.and take dict. as an argument
my_dict.update({"name":"target"})
print(my_dict)

{'hp': 'shimla', 'up': 'lucknow', 'name': 'target'}


In [ ]:
#conditional statement
#if
#elif
#else
age= int(input ("enter your age "))
if age>60 :
  print("you're too old to marry")
elif age<18 :
  print("youre too young to marry")
else :
  print("you will find a perfect match for you")

enter your age 23
you will find a perfect match for you


In [ ]:
my_sub="python"
print(my_sub[0])

p


In [ ]:
my_sub="python"
for i in my_sub:
 print(i)

p
y
t
h
o
n


In [ ]:
my_sub="saksham sharma"
for i in my_sub:
  print(i)

s
a
k
s
h
a
m
 
s
h
a
r
m
a


In [ ]:
#range (SP,EP,SS)
#SP--
#EP--ENDING POINT
#SS--STOP SIZE,BY DEFAULT IT IS OVER

In [ ]:
#range(0,6,2) #range (0,6)
#0            #0
#1

In [ ]:
for i in range(6) :
  print(i)


0
1
2
3
4
5


In [ ]:
#list
my_list=[1,2,3,45,]
for i in my_list:
  print(i)

1
2
3
45


In [ ]:
#loop control statement
#break--this statement break the loop
i = 0
while i<5:
  i+=1
  if i==3:
    break
  print(i)

1
2


In [ ]:
#while loop
i=0
while i>5:
  print(i)
i+=1

In [ ]:
#continue--this statement skip the current iteration
i = 0
while i<5:
  i+=1
  if i==3:
    continue
  print(i)

1
2
4
5


In [ ]:
#keyword argument
def interest(p,r,t):
  i = (p*r*t)/100
  return i

In [ ]:
print(interest(r=10,p=1000,t=2))

NameError: name 'interest' is not defined

In [ ]:
test(2,3,4,5,6)

NameError: name 'test' is not defined

In [ ]:
def sum_number(*args):
  sum = 0
  for num in args:
    sum+=num
    return sum

In [ ]:
sum_number(1,2,3,4,5,6,)

NameError: name 'sum_number' is not defined

In [ ]:
def sum_number(*args):
  sum = 0
  for num in args:
    sum+=num
  return sum

In [ ]:
sum_number(1,2,3,4,5,6,)

NameError: name 'sum_number' is not defined

In [ ]:
def sum_number(*args):
  sum = 0
  for num in args:
    sum+=num
  return sum

In [ ]:
sum_number(1,2,3,4,5,6,)

21

In [ ]:
def sum_number(*args):
  sum = 0
  for num in args:
    sum+=num
  return sum

In [ ]:
sum_number(1,2,3,4,5,6,)

21

In [ ]:
#numpy -- numerical python
#it is used for mathematics
#data structure of numpie is multidimensional
#data structure  of numpy is multidimensional array

In [ ]:
import numpy as np

In [ ]:
#one dimensional array
oned_array = np.array([1,2,3,4])
print(oned_array)

[1 2 3 4]


In [ ]:
#two dimensional array
twod_array = np.array([[1,2,3],[4,5,6]])
print (twod_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
#size -- represent number of item to the array
print()

In [ ]:
#indexing

In [ ]:
#vv

In [ ]:
import numpy as np
my_array= np.array([1,2,3,4])
print(my_array)

[1 2 3 4]


In [ ]:
power_array = np.power(my_array, 2)
print(power_array)

[ 1  4  9 16]


In [ ]:
log_array = np.log(my_array)
print(log_array)

[0.         0.69314718 1.09861229 1.38629436]


In [ ]:
log2_array = np.log2(my_array)
print(log2_array)

[0.        1.        1.5849625 2.       ]


In [ ]:
log10_array = np.log10(my_array)
print(log10_array)

[0.         0.30103    0.47712125 0.60205999]


In [ ]:
exp_array = np.exp(my_array)
print(exp_array)

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
import matplotlib.pyplot as plt


In [ ]:
Def add():
a = int(input("enter first number:"))
b

In [ ]:
Print (area_perimeter(10,

In [ ]:
#data structure- it is a fundamental for any programming lang. around which programme is built.
type of data structure-
mutuable dt - changeable after being built.
iske bhi types -
list
dictionary
set.

SyntaxError: invalid syntax (ipython-input-1392739301.py, line 2)

In [ ]:
slicing in string-
grab the data upto desiganted point
my_sub="machine learning"
my_sub(SI :L )

immutable DT
not changeable after being built.
types
string
couple
number

In [ ]:
#range
for i in range(0,6,1):
print(i)

In [ ]:
len(my_sub) this function defines the length of the string.

In [ ]:
from transformers import pipeline
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
text -"""The global shift toward renewable energy is accelerating, driven by concerns over climate change and energy security. Solar and wind power installations have reached record levels worldwide."""
summary = summarizer(text, max_length=30, min_length=10, do_sample=False)
print(summary[0])

Device set to use cpu


NameError: name 'text' is not defined

In [ ]:
pract

STRING-sequence of character or icon.it is enclosed by ",' or"'.it is immutable type data structure.it could be either word,sentence,paragraph or an entire encyclopedia.